### ISSUE TITLE
Feature: Open back office / front end link in new tab if not the current view

### ISSUE THREAD

**Issue by NikRimington** [nul800sebastiaan/UmbracoProductivityExtension#2]
Is it possible for the respective links to identify if they are already on the front/back end of the website and open the alternatives in new tabs?

e.g. If I was visiting "https://mywebsite.com" and I click "Umbraco back office", it should open that in a new tab.
If I was visiting "https://mywebsite.com/umbraco" and I clicked "Open front end" it should open that in a new tab.

**Comment by nul800sebastiaan** [comment]
In the options, the "open in backoffice" button can be configured to always open in a new tab. Guess I can make a toggle for the frontend button as well. 
Good point on checking if the URL already contains `/umbraco` or not. That should complicate things very nicely.. 😅

**Comment by nul800sebastiaan** [comment]
I fixed it! But had already submitted an older version for review, so I'll need to wait for that one to pass before I can upload v2.2.0 🙏 It'll take a few days I suppose :)

**Comment by nul800sebastiaan** [comment]
They're getting faster at approving! This change is now live @NikRimington - https://chrome.google.com/webstore/detail/umbraco-productity/kepkgaeokeknlghbiiipbhgclikjgkdp/related?hl=en&authuser=1
